"""new fields in user model

Revision ID: b18b3b0c9874
Revises: 0296eade313d
Create Date: 2023-02-24 09:11:17.266400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18b3b0c9874'
down_revision = '0296eade313d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('advisor_full_name', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('fapesp_process_number', sa.String(length=140), nullable=True))
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('fapesp_process_number')
        batch_op.drop_column('advisor_full_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
